Repository acl-org/acl-anthology, pull requests merged in 2021-08, with the labels that each got.

#1417 Ingested MT Summit 2001.
  bin/write_bibkeys_to_xml.py
  data/xml/2001.mtsummit.xml
Labels: ingestion

#1423 Ingested MT Summit 2003.
  data/xml/2003.mtsummit.xml
Labels: ingestion

#1392 Ingest mtsummit 1989
  data/xml/1989.mtsummit.xml
Labels: ingestion

#1428 Ingested MT Summit 2005.
  data/xml/2005.mtsummit.xml
Labels: ingestion

#1447 Ingested MT Summit 2015.
  data/xml/2015.mtsummit.xml
Labels: ingestion

#1443 Ingested MT Summit 2009.
  data/xml/2009.mtsummit.xml
Labels: ingestion

#1462 Ingested TC 1980.
  data/xml/1980.tc.xml
  data/yaml/venues.yaml
Labels: ingestion

#1410 add video links for HumEval workshop at EACL
  data/xml/2021.humeval.xml
Labels: ingestion

#1508 ingested tc 1997
  data/xml/1997.tc.xml
Labels: ingestion

#1494 ingested tc 1984
  data/xml/1984.tc.xml
  data/xml/schema.rnc
Labels: ingestion

#1504 ingested tc 1995
  data/xml/1995.tc.xml
Labels: ingestion

#1471 Ingested MTSUMMIT 2021
  data/xml/2021.mtsummit.xml
  data/xml/W19.xml
Labels: ingestion

#1505 Sigdial 2021 Ingestion
  data/xml/2021.sigdial.xml
  data/yaml/sigs/sigdial.yaml
Labels: ingestion

#1456 Ingested TMI 1997.
  data/xml/1997.tmi.xml
  data/yaml/venues.yaml
Labels: ingestion

#1466 Ingested IWSLT 2005.
  data/xml/2005.iwslt.xml
Labels: ingestion

#1503 ingested tc 1994
  data/xml/1994.tc.xml
Labels: ingestion

#1502 ingested tc 1993
  data/xml/1993.tc.xml
Labels: ingestion

#1513 Ingest tc 2002
  data/xml/2002.tc.xml
  data/xml/2005.mtsummit.xml
Labels: ingestion

#1535 Fixed name on 2020.nlpcovid19-2.31
  data/xml/2020.nlpcovid19.xml
Labels: correction, metadata

#1500 ingested tc 1991
  data/xml/1991.tc.xml
Labels: ingestion

#1525 Ingest tc 1988
  data/xml/1988.tc.xml
Labels: ingestion

#1557 Attachment removal
  data/xml/2021.acl.xml
  data/xml/2021.findings.xml
Labels: correction, pending

#1533 ccl 2021 ingestion
  bin/author_names_to_variants.py
  bin/ingest.py
  data/xml/2021.ccl.xml
Labels: ingestion
