Repository acl-org/acl-anthology, pull requests merged in 2024-04, with the labels that each got.

#3202 Add Citeproc functionality
  .github/workflows/code-quality.yml
  .github/workflows/preview.yml
  bin/create_hugo_yaml.py
  python/CHANGELOG.md
  python/acl_anthology/collections/paper.py
  python/acl_anthology/collections/volume.py
  python/acl_anthology/data/acl.csl
  python/acl_anthology/people/name.py
  python/acl_anthology/utils/__init__.py
  python/acl_anthology/utils/citation.py
  python/docs/api/utils.md
  python/poetry.lock
  python/pyproject.toml
  python/tests/collections/paper_test.py
  python/tests/collections/volume_test.py
  python/tests/people/name_test.py
Labels: python-library

#3169 Ingestion: GEM 2023
  data/xml/2023.emnlp.xml
  data/xml/2023.gem.xml
Labels: ingestion

#3244 [ACL 2022] Fixed incorrect video matching
  data/xml/2022.acl.xml
Labels: correction
