Repository acl-org/acl-anthology, pull requests merged in 2024-01, with the labels that each got.

#3022 Fix tex-math to unicode serialization
  bin/anthology/texmath.py
  tests/test_tex_math.py
Labels: bug

#2993 Ingestion: swisstext
  data/xml/2023.swisstext.xml
  data/yaml/venues/swisstext.yaml
Labels: ingestion

#3046 Added ACL 2023 videos
  data/xml/2022.cl.xml
  data/xml/2022.clinicalnlp.xml
  data/xml/2022.findings.xml
  data/xml/2022.semeval.xml
  data/xml/2022.tacl.xml
  data/xml/2023.acl.xml
  data/xml/2023.bea.xml
  data/xml/2023.bionlp.xml
  data/xml/2023.cl.xml
  data/xml/2023.clinicalnlp.xml
  data/xml/2023.codi.xml
  data/xml/2023.findings.xml
  data/xml/2023.law.xml
  data/xml/2023.matching.xml
  data/xml/2023.nlp4convai.xml
  data/xml/2023.nlrse.xml
  data/xml/2023.repl4nlp.xml
  data/xml/2023.semeval.xml
  data/xml/2023.sicon.xml
  data/xml/2023.sigmorphon.xml
  data/xml/2023.sustainlp.xml
  data/xml/2023.tacl.xml
  data/xml/2023.trustnlp.xml
  data/xml/2023.wassa.xml
  data/xml/2023.wnu.xml
Labels: enhancement

#2973 Multi3Generation Ingestion
  data/xml/2023.eamt.xml
  data/xml/2023.multi3generation.xml
  data/yaml/venues/multi3generation.yaml
Labels: ingestion

#2992 Ingestion: ICNLSP 2023
  data/xml/2023.icnlsp.xml
Labels: ingestion
